# Generated by Django 4.2.20 on 2025-04-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artista',
            new_name='ArtistaModel',
        ),
        migrations.RenameModel(
            old_name='Musica',
            new_name='MusicaModel',
        ),
    ]
